<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:reqsel="http://www.aib.ie/schemas/Request/ClientViewReferenceDataLookup" 
	xmlns:respsel="http://www.aib.ie/schemas/Response/ClientViewReferenceDataLookup" 
	xmlns:tns="http://www.aib.ie/wsdl/ClientViewReferenceDataLookup" 
	name="ClientViewReferenceDataLookup" 
	targetNamespace="http://www.aib.ie/wsdl/ClientViewReferenceDataLookup">
	<wsdl:types>
		<xs:schema>
			<xs:import namespace="http://www.aib.ie/schemas/Request/ClientViewReferenceDataLookup" schemaLocation="../../schemas/MAS/ClientViewReferenceDataLookupRequest.xsd"/>
			<xs:import namespace="http://www.aib.ie/schemas/Response/ClientViewReferenceDataLookup" schemaLocation="../../schemas/MAS/ClientViewReferenceDataLookupResponse.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="ResponseMessage">
		<wsdl:part name="body" element="respsel:Response"/>
	</wsdl:message>
	<wsdl:message name="RequestMessage">
		<wsdl:part name="body" element="reqsel:Request"/>
	</wsdl:message>
	<wsdl:portType name="ClientViewReferenceDataLookupPortType">
		<wsdl:operation name="ClientViewReferenceDataLookupOperation" parameterOrder="input">
			<wsdl:input message="tns:RequestMessage"/>
			<wsdl:output message="tns:ResponseMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ClientViewReferenceDataLookupBinding" type="tns:ClientViewReferenceDataLookupPortType">
		<wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<wsdl:operation name="ClientViewReferenceDataLookupOperation">
			<wsdlsoap:operation soapAction="ClientViewReferenceDataLookupOperation"/>
			<wsdl:input>
				<wsdlsoap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<wsdlsoap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ClientViewReferenceDataLookupService">
		<wsdl:documentation/>
		<wsdl:port name="ClientViewReferenceDataLookupPort" binding="tns:ClientViewReferenceDataLookupBinding">
			<wsdlsoap:address location="http://localhost:9731/plserver"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
