/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '53458' at '12/03/15 16:02' with Gradle 2.3
 *
 * @author 53458, @date 12/03/15 16:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
